### ISSUE TITLE
乱码

### ISSUE THREAD

**Issue by liuzhihang** [cmushroom/redis-pro#13]
![image](https://user-images.githubusercontent.com/26057042/126139717-da2aa60c-4e48-489a-a359-baf6991e0a2f.png)

这些应该是乱码吧。 就是标题右边的，还是我设置的不对。

**Comment by chengpan168** [comment]
这里不是乱码，是故意放上去tips， 鼠标放上去会有相应的提示

**Comment by chengpan168** [comment]
![image](https://user-images.githubusercontent.com/2920167/126140324-f2a7c8d0-61bc-4642-9dd8-ae7328c13e45.png)
不过样式有些差异， 我这里是这样的

**Comment by liuzhihang** [comment]
![image](https://user-images.githubusercontent.com/26057042/126140581-82ec6877-815e-4b3e-97ea-8b6e7a3d3182.png)

我的也是 我是 Intel 的

**Comment by liuzhihang** [comment]
看着小方块 我还以为是乱码了，是不是系统识别不了小问号

**Comment by chengpan168** [comment]
看到你的另个issue 像是乱码了， db 的那个符号也是问号了

**Comment by chengpan168** [comment]
![image](https://user-images.githubusercontent.com/2920167/126141156-e542cf2b-fab1-487f-8cc3-a30c8f397188.png)
看到你的另个issue 像是乱码了， db 的那个符号也是问号了

**Comment by liuzhihang** [comment]
对对，我也看到了。这个有啥解决办法嘛

**Comment by chengpan168** [comment]
重启试试， 我还没有遇到过

**Comment by liuzhihang** [comment]
我退出重新进来还是这样，电脑倒是好久没重启了。

**Comment by chengpan168** [comment]
app也是最新的版本吧

**Comment by liuzhihang** [comment]
![image](https://user-images.githubusercontent.com/26057042/126142879-970632cc-0d48-4d01-a0d8-0029bdaaf363.png)
是的 通过 brew 安装的

**Comment by chengpan168** [comment]
我优化一下这里的代码， 明天试一下

**Comment by chengpan168** [comment]
d634fea8797742e9e90aa207d86189d57ad4894c 已修复
