### ISSUE TITLE
按钮字体颜色不正确

### ISSUE THREAD

**Issue by liuzhihang** [cmushroom/redis-pro#14]
![image](https://user-images.githubusercontent.com/26057042/126140246-0d8a41ca-5d5b-417b-b981-59a07bbaa9d0.png)

在 light 模式下按钮颜色不正确

**Comment by chengpan168** [comment]
没有正确识别这些符号
![image](https://user-images.githubusercontent.com/2920167/126140974-a924aabe-fa06-46b7-82d5-a8f34b93c382.png)

**Comment by liuzhihang** [comment]
这些符号是需要配置字体还是什么

**Comment by chengpan168** [comment]
不需要的， 这些就是emoji符号

**Comment by chengpan168** [comment]
d634fea8797742e9e90aa207d86189d57ad4894c 已修复
