### ISSUE TITLE
homebrew 安装不了

### ISSUE THREAD

**Issue by teg1c** [cmushroom/redis-pro#18]
<img width="1495" alt="QQ20210806-101201@2x" src="https://user-images.githubusercontent.com/27796058/128445435-ef78b235-ba6b-4a00-8610-c4a9011cb799.png">

**Comment by chengpan168** [comment]
brew 可以安装其它应用吗， 使用 `brew doctor`,  `brew search redis-pro` 看一下，  给终端开个代理尝试一下，国内github 很慢
