### ISSUE TITLE
建议增加 ssh key 的登录方式

### ISSUE THREAD

**Issue by bingoku** [cmushroom/redis-pro#20]
RT:
建议增加 ssh key 的登录方式

**Comment by chengpan168** [comment]
嗯， 下一个会增加的

**Comment by chengpan168** [comment]
最近在看这个问题， swift-nio-ssh 暂时不支持， 看到有pr在开发， 不过进度比较慢， 现在还没有看到更好的方案， 计划等官方库支持后会同步加上了
