### ISSUE TITLE
端口输入框获得焦点时鼠标往下移动会有一个虚框出现【1.4.2】

### ISSUE THREAD

**Issue by ydq** [cmushroom/redis-pro#24]
直接上图：
![redis-pro-port](https://user-images.githubusercontent.com/8097340/152713493-3460400c-121b-4eb7-8420-c975cc2d4256.gif)

**Comment by chengpan168** [comment]
只有在port输入框里才有虚框吗，  其它输入框正常吗

**Comment by ydq** [comment]
> 只有在port输入框里才有虚框吗， 其它输入框正常吗

在我这边 密码会提示一个 悬浮的 密码 悬浮，然后再去看 port 框的时候 框框也变小了，CMD+Q 彻底退出后再打开
Port 框获取焦点，然后鼠标再悬浮 Port 下面一点 框框就变成 原来那个大的了

下面是变小后的框框现象，MacOS版本 12.2 / intel

![redis-port](https://user-images.githubusercontent.com/8097340/152754942-30a79a6d-edfa-4b31-bc8c-05c5067d65d3.gif)

**Comment by ydq** [comment]
> 只有在port输入框里才有虚框吗， 其它输入框正常吗

目前发现的只有 port 框 和 password 框会有悬浮，但是 password 框是正常的系统密码填充的提示

**Comment by chengpan168** [comment]
找到原因了， 是在密码输入框前一个输入框会自动弹出用户名相关提示， 已修复
