### ISSUE TITLE
1.4.3 翻页 ERROR 弹窗

### ISSUE THREAD

**Issue by ydq** [cmushroom/redis-pro#27]
首先是页码计算有误，其次直接点击下一页按钮，出现 error 弹窗

<img width="927" alt="iShot2022-02-08 09 26 23" src="https://user-images.githubusercontent.com/8097340/152900445-8b56076c-515c-4dc8-85b4-3e6940da60a5.png">

**Comment by chengpan168** [comment]
已经修复了， 不发新版本了， 重新打个包， 还是1.4.3， 下载试一下

**Comment by ydq** [comment]
> 已经修复了， 不发新版本了， 重新打个包， 还是1.4.3， 下载试一下

可以了，辛苦大佬
