### ISSUE TITLE
ssh使用密钥连接

### ISSUE THREAD

**Issue by soxft** [cmushroom/redis-pro#28]
ssh 通道能不能增加使用密钥呢？

**Comment by chengpan168** [comment]
计划增加这个功能，现存的问题修复掉之后，这个是优先开发。

**Comment by soxft** [comment]
感谢

**Comment by chengpan168** [comment]
最近在看这个问题， swift-nio-ssh 暂时不支持， 看到有pr在开发， 不过进度比较慢， 现在还没有看到更好的方案， 计划等官方库支持后会同步加上了

**Comment by soxft** [comment]
好的，主要是服务器我基本上都禁止了密码登录，全部采用密钥，之前被别人爆破密码
