### ISSUE TITLE
zset(sorted set)里面的元素没有按照顺序返回

### ISSUE THREAD

**Issue by ydq** [cmushroom/redis-pro#31]
rt: zset(sorted set)里面的元素没有按照顺序返回

个人猜测 当前是使用 zscan 来返回的，但是 zset 本身是个有顺序的结构，建议可以使用`zrange  withscores` 来按顺序返回里面的元素

**Comment by chengpan168** [comment]
在没有使用搜索条件的时候， 或许可以使用zrange查询分页，有关键的时候使用zscan

**Comment by chengpan168** [comment]
done
