### ISSUE TITLE
左侧列表刷新，没有清空选中项，导致无法刷新 value 的 bug

### ISSUE THREAD

**Issue by ydq** [cmushroom/redis-pro#33]
先直接说复现过程：
1. 准备数据，创建两个key
    ~~~bash
    > SET test:aaa aaa

    > SET test:bbb bbb
    ~~~
2. 在 redis-pro 上搜索key `test:aaa` ，并选中 这个搜索到的唯一key，此时能获取到值是 "aaa"
3. 在 redis-pro 上搜索key `test:bbb`，此时出现 bug，因为默认选中了第一项，猜测可能是没有触发redis-pro 内部的某些key 变更的事件，然后认为还是旧的 key，所以value 还是上一次选中的key所对应的value ”aaa“，而且就算点击 refresh 按钮，也无法获得当前真正选中的key所对应的值

此问题也出现在翻页的场景下，即当选中某一个key，翻页后，依旧会默认选中相同位置的key，点击这个key 无法刷新值

不确定我表述的是否明了，如果有需要可以留言~

**Comment by chengpan168** [comment]
本地已经复现了， 周末看一下
