### ISSUE TITLE
1.4.4 版本 左侧favorites列表删除时没有确认弹窗

### ISSUE THREAD

**Issue by fbzl** [cmushroom/redis-pro#35]
感谢作者开发的工具

左侧favorites列表
删除时没有确认弹窗
不能拖拽移动位置

右侧配置页面
开启SSH选项是，高度显示有问题
![](https://user-images.githubusercontent.com/703727/156887091-7a7e3f2a-3926-4c13-9055-54b96865159e.png)

**Comment by chengpan168** [comment]
高度问题我修一下， 前几个属于添加新功能了， 会排在功能列表里
