### ISSUE TITLE
无法从Dock栏恢应用图标复最小化的窗口

### ISSUE THREAD

**Issue by ydq** [cmushroom/redis-pro#38]
系统版本：12.3.1 (21E258) （Apple M1）
软件版本：1.4.5 (12)

操作如下：
1. `打开系统偏好设置` - `程序坞与菜单栏` - ☑️`将窗口最小化至应用程序图标`
    ![image](https://user-images.githubusercontent.com/8097340/168221404-d2f05ee6-a129-40fe-ad15-ea50a9931998.png)
    > 开启此功能本意是想节省一下 dock 栏的空间，让 dock 栏能放下更多的常用图标，而不被最小化窗口给挤占
2. 打开其他任意软件（目前测试的有 Sequel Ace、Medis2 等一些常用软件）点击最小化按钮，可以自由的最小化至图标之中，点击Dock 栏图标能恢复窗口 
    ![sample](https://user-images.githubusercontent.com/8097340/168222829-5bf16ae9-4ff7-4985-b21a-44908be4cc66.gif)
但是 redis-pro 最小化到图标之后，**再次点击图标，无法恢复最小化的窗体**，必须要右键菜单中才能恢复
![image](https://user-images.githubusercontent.com/8097340/168223039-d3fe7e2b-0e8d-4e15-b79e-abb3aa9584ff.png)

描述的可能不够清晰，不知道能否复现😂

**Comment by chengpan168** [comment]
懂了，还没有这样设置过，晚会试下

**Comment by chengpan168** [comment]
这个像是swiftui 的一个bug, 回调方法不能被触发,  https://developer.apple.com/forums/thread/706772?answerId=715063022#715063022

**Comment by chengpan168** [comment]
没有完美解决， 有点瑕疵

**Comment by ydq** [comment]
> 没有完美解决， 有点瑕疵

猜测是不是 只有失去焦点（如点击一下桌面） 才能触发，否则直接最小化之后立刻点击还是无法恢复～
