### ISSUE TITLE
Test connection 之后 Loading... 窗口不消失

### ISSUE THREAD

**Issue by ydq** [cmushroom/redis-pro#44]
RT：Test connection 之后 Loading... 窗口不消失

版本：2.0 RC
系统：12.4 / M1

但是底部的 文案提示 "Connect successed!"

不确定是不是个例

![image](https://user-images.githubusercontent.com/8097340/173618429-d890a15c-6e75-4245-bc51-4192da42d6db.png)

**Comment by chengpan168** [comment]
重新下载可以解决， 这个已经修复了
