### ISSUE TITLE
模糊查找key（scan）能否不自动往后加载全部，提升可用率

### ISSUE THREAD

**Issue by ydq** [cmushroom/redis-pro#46]
作者别介意哈，可能是个例伪需求：

我们现在线上经常有 1.5亿 ～ 2亿 的key

当使用 通配符 【key_prefix*】来查找的时候，个人 猜测 redis-pro 因为要等到全部 scan 完才能使用，导致这个过程非常长，几乎是不可用的状态（个人猜测 redis-pro 是需要把上亿的 key 全部扫一次，直至 cursor == ‘0’ 才能使用）

![redis-pro](https://user-images.githubusercontent.com/8097340/177536330-8a553008-723a-4ee7-ac3e-c8a88e4b3fc2.gif)

和  medis2 来做对比，虽然他没有做成分页形式，但他的模式是 scan 到限定的条数就不再继续了，也有一个翻页大小的概念，除非手动点击加载更多按钮才会继续下一页，而且列表时异步出结果的，有一条显示一条，而不必等到这一批加载完才可用
![medis2](https://user-images.githubusercontent.com/8097340/177537179-ac36ff1c-0f25-46cb-8e3a-5ffa993a97b7.gif)

如上图  medis2 搜索之后，很快就可用了，而 redis-pro  一直在 loading 不可用的状态

结合目前 redis-pro 是不支持跳页的，翻页到下一页 也只能通过点击下一页按钮来翻页，两者其实很相似
所以 通配符搜索的时候  是否可以  ：

1. 页码处 更新成为  1/next 或 1/∞ 这样的，后面总也码数不需要立刻计算准确的有多少页
2. 当前翻页 数据总数不满足  pageNo * pageSize 且 cursor != ‘0’ 的时候 自动继续 scan，直至满足当前页的数据量
3. 当前翻页这一页数据没加载完或者 cursor == ‘0’的时候下一页按钮不可点击
4. 列表异步渲染，scan到一条立刻显示一条，改进全局加载的 loading 遮罩效果，而不是必须要等待全部获取到了再显示
    > 主要是为了满足 在巨量的key中查找少量的key，比如我有一批前缀的key 可能只有30条，单总key有上亿，每次找一条都需要很久的情况，能有一条先显示一条比起让用户一直等到满足这一页所有或者scan完毕要好
5. 用户点击下一页翻页按钮的时候 出发第2步加载数据
6. 当数据加载完了 cursor == ‘0’ 之后，更新第一步的总页码

**Comment by chengpan168** [comment]
感谢宝贵建议！主要是不想放弃总数量的功能。
这个问题是由于一次模糊查询会有两个任务，一个查询数据，数据任务扫到一页的时候就停止了；一个计算总数量，计算数量的一直扫描到结束，数据多的话会比较耗时。
跳页是可以做到的，是早期的分页模式不支持，一直没加上😀，之前有几十万的key需要几秒钟，你这个这么大量应该会比较慢了。
我觉得你说的异步计算数量挺好的，不阻塞查询，只要总分页大于当前页码就可以翻，这里的异步扫描总数量任务还没太想好，在前一次没有结束前又进行了搜索，怎么控制始终只有一个数据计算任务。
