### ISSUE TITLE
多Tab（多个连接）的情况下，窗体失去焦点后重新点击界面，会自动强制切换到第一个tab

### ISSUE THREAD

**Issue by ydq** [cmushroom/redis-pro#55]
rt：多Tab（多个连接）的情况下，窗体失去焦点后重新点击界面，会自动强制切换到第一个tab

盲猜 不确定是不是为了尝试修复最小化到dock，点击dock栏图标恢复窗体的那个功能 引起的。

**Comment by chengpan168** [comment]
是的， 先回滚了
