### ISSUE TITLE
编辑value 输入英文引号会被转换成中文引号

### ISSUE THREAD

**Issue by Mike-Acb** [cmushroom/redis-pro#8]
Version 1.1.1 (3)
OS: 11.2.3

如果光标在引号附近修改也会被转换

🌰
https://public-mike8.oss-cn-shanghai.aliyuncs.com/Screen Recording 2021-07-11 at 15.54.27.mov?versionId=CAEQIRiBgMDF0KLS1BciIDJhNTk1ZDY4MWVlZTQ1ODI4M2ZiMjlhYjNiOWM3MDVk

**Comment by chengpan168** [comment]
有一个方案是在输入法里设置，不要自动切换双引号，代码里怎么处理还没有想到比较好的解决方案，我再研究研究

**Comment by chengpan168** [comment]
![image](https://user-images.githubusercontent.com/2920167/125222671-072e2500-e2fd-11eb-84cf-0a7ef36dfeb0.png)

**Comment by Mike-Acb** [comment]
关闭智能引号可以啦。。感谢

**Comment by chengpan168** [comment]
0b1e8383ab217fdac6c3ff619b23f36323b74d73 已优化，下个版本修复
